// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bl10.proto

package bl10

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LocationPacket_Status int32

const (
	LocationPacket_TIMING_REPORT              LocationPacket_Status = 0
	LocationPacket_FIXED_DISTANCE_REPORT      LocationPacket_Status = 1
	LocationPacket_GPS_REUPLOAD               LocationPacket_Status = 2
	LocationPacket_LJDW_REPORT                LocationPacket_Status = 3
	LocationPacket_LOCK_REPORT                LocationPacket_Status = 4
	LocationPacket_UNLOCK_REPORT              LocationPacket_Status = 5
	LocationPacket_LOW_INTERNAL_BATTERY_ALARM LocationPacket_Status = 6
	LocationPacket_LOW_BATTERY_SHUTDOWN       LocationPacket_Status = 7
	LocationPacket_ABNORMAL_ALARM             LocationPacket_Status = 8
	LocationPacket_ABNORMAL_UNLOCKING_ALARM   LocationPacket_Status = 9
)

var LocationPacket_Status_name = map[int32]string{
	0: "TIMING_REPORT",
	1: "FIXED_DISTANCE_REPORT",
	2: "GPS_REUPLOAD",
	3: "LJDW_REPORT",
	4: "LOCK_REPORT",
	5: "UNLOCK_REPORT",
	6: "LOW_INTERNAL_BATTERY_ALARM",
	7: "LOW_BATTERY_SHUTDOWN",
	8: "ABNORMAL_ALARM",
	9: "ABNORMAL_UNLOCKING_ALARM",
}

var LocationPacket_Status_value = map[string]int32{
	"TIMING_REPORT":              0,
	"FIXED_DISTANCE_REPORT":      1,
	"GPS_REUPLOAD":               2,
	"LJDW_REPORT":                3,
	"LOCK_REPORT":                4,
	"UNLOCK_REPORT":              5,
	"LOW_INTERNAL_BATTERY_ALARM": 6,
	"LOW_BATTERY_SHUTDOWN":       7,
	"ABNORMAL_ALARM":             8,
	"ABNORMAL_UNLOCKING_ALARM":   9,
}

func (x LocationPacket_Status) String() string {
	return proto.EnumName(LocationPacket_Status_name, int32(x))
}

func (LocationPacket_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7cb77491feb77e2e, []int{2, 0}
}

type Lock struct {
	Imei                 string   `protobuf:"bytes,1,opt,name=imei,proto3" json:"imei,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Lock) Reset()         { *m = Lock{} }
func (m *Lock) String() string { return proto.CompactTextString(m) }
func (*Lock) ProtoMessage()    {}
func (*Lock) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cb77491feb77e2e, []int{0}
}

func (m *Lock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lock.Unmarshal(m, b)
}
func (m *Lock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lock.Marshal(b, m, deterministic)
}
func (m *Lock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lock.Merge(m, src)
}
func (m *Lock) XXX_Size() int {
	return xxx_messageInfo_Lock.Size(m)
}
func (m *Lock) XXX_DiscardUnknown() {
	xxx_messageInfo_Lock.DiscardUnknown(m)
}

var xxx_messageInfo_Lock proto.InternalMessageInfo

func (m *Lock) GetImei() string {
	if m != nil {
		return m.Imei
	}
	return ""
}

type LockStatus struct {
	Timestamp            int64           `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Imei                 string          `protobuf:"bytes,2,opt,name=imei,proto3" json:"imei,omitempty"`
	GpsEnabled           bool            `protobuf:"varint,3,opt,name=gps_enabled,json=gpsEnabled,proto3" json:"gps_enabled,omitempty"`
	IsCharching          bool            `protobuf:"varint,4,opt,name=is_charching,json=isCharching,proto3" json:"is_charching,omitempty"`
	IsLocked             bool            `protobuf:"varint,5,opt,name=is_locked,json=isLocked,proto3" json:"is_locked,omitempty"`
	LocationPacket       *LocationPacket `protobuf:"bytes,6,opt,name=location_packet,json=locationPacket,proto3" json:"location_packet,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *LockStatus) Reset()         { *m = LockStatus{} }
func (m *LockStatus) String() string { return proto.CompactTextString(m) }
func (*LockStatus) ProtoMessage()    {}
func (*LockStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cb77491feb77e2e, []int{1}
}

func (m *LockStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LockStatus.Unmarshal(m, b)
}
func (m *LockStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LockStatus.Marshal(b, m, deterministic)
}
func (m *LockStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockStatus.Merge(m, src)
}
func (m *LockStatus) XXX_Size() int {
	return xxx_messageInfo_LockStatus.Size(m)
}
func (m *LockStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_LockStatus.DiscardUnknown(m)
}

var xxx_messageInfo_LockStatus proto.InternalMessageInfo

func (m *LockStatus) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *LockStatus) GetImei() string {
	if m != nil {
		return m.Imei
	}
	return ""
}

func (m *LockStatus) GetGpsEnabled() bool {
	if m != nil {
		return m.GpsEnabled
	}
	return false
}

func (m *LockStatus) GetIsCharching() bool {
	if m != nil {
		return m.IsCharching
	}
	return false
}

func (m *LockStatus) GetIsLocked() bool {
	if m != nil {
		return m.IsLocked
	}
	return false
}

func (m *LockStatus) GetLocationPacket() *LocationPacket {
	if m != nil {
		return m.LocationPacket
	}
	return nil
}

type LocationPacket struct {
	LockTimestamp        int64                 `protobuf:"varint,1,opt,name=lock_timestamp,json=lockTimestamp,proto3" json:"lock_timestamp,omitempty"`
	Location             *PositionPackage      `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Status               LocationPacket_Status `protobuf:"varint,3,opt,name=status,proto3,enum=LocationPacket_Status" json:"status,omitempty"`
	BaseStation          *BaseStation          `protobuf:"bytes,4,opt,name=base_station,json=baseStation,proto3" json:"base_station,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *LocationPacket) Reset()         { *m = LocationPacket{} }
func (m *LocationPacket) String() string { return proto.CompactTextString(m) }
func (*LocationPacket) ProtoMessage()    {}
func (*LocationPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cb77491feb77e2e, []int{2}
}

func (m *LocationPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocationPacket.Unmarshal(m, b)
}
func (m *LocationPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocationPacket.Marshal(b, m, deterministic)
}
func (m *LocationPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocationPacket.Merge(m, src)
}
func (m *LocationPacket) XXX_Size() int {
	return xxx_messageInfo_LocationPacket.Size(m)
}
func (m *LocationPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_LocationPacket.DiscardUnknown(m)
}

var xxx_messageInfo_LocationPacket proto.InternalMessageInfo

func (m *LocationPacket) GetLockTimestamp() int64 {
	if m != nil {
		return m.LockTimestamp
	}
	return 0
}

func (m *LocationPacket) GetLocation() *PositionPackage {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *LocationPacket) GetStatus() LocationPacket_Status {
	if m != nil {
		return m.Status
	}
	return LocationPacket_TIMING_REPORT
}

func (m *LocationPacket) GetBaseStation() *BaseStation {
	if m != nil {
		return m.BaseStation
	}
	return nil
}

type PositionPackage struct {
	Latitude             float32  `protobuf:"fixed32,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float32  `protobuf:"fixed32,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Accuracy             float32  `protobuf:"fixed32,3,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	Course               int32    `protobuf:"varint,4,opt,name=course,proto3" json:"course,omitempty"`
	Speed                float32  `protobuf:"fixed32,5,opt,name=speed,proto3" json:"speed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PositionPackage) Reset()         { *m = PositionPackage{} }
func (m *PositionPackage) String() string { return proto.CompactTextString(m) }
func (*PositionPackage) ProtoMessage()    {}
func (*PositionPackage) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cb77491feb77e2e, []int{3}
}

func (m *PositionPackage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PositionPackage.Unmarshal(m, b)
}
func (m *PositionPackage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PositionPackage.Marshal(b, m, deterministic)
}
func (m *PositionPackage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PositionPackage.Merge(m, src)
}
func (m *PositionPackage) XXX_Size() int {
	return xxx_messageInfo_PositionPackage.Size(m)
}
func (m *PositionPackage) XXX_DiscardUnknown() {
	xxx_messageInfo_PositionPackage.DiscardUnknown(m)
}

var xxx_messageInfo_PositionPackage proto.InternalMessageInfo

func (m *PositionPackage) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *PositionPackage) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *PositionPackage) GetAccuracy() float32 {
	if m != nil {
		return m.Accuracy
	}
	return 0
}

func (m *PositionPackage) GetCourse() int32 {
	if m != nil {
		return m.Course
	}
	return 0
}

func (m *PositionPackage) GetSpeed() float32 {
	if m != nil {
		return m.Speed
	}
	return 0
}

type BaseStation struct {
	Mcc                  int32    `protobuf:"varint,1,opt,name=mcc,proto3" json:"mcc,omitempty"`
	Mnc                  int32    `protobuf:"varint,2,opt,name=mnc,proto3" json:"mnc,omitempty"`
	Lac                  int32    `protobuf:"varint,3,opt,name=lac,proto3" json:"lac,omitempty"`
	Ci                   int32    `protobuf:"varint,4,opt,name=ci,proto3" json:"ci,omitempty"`
	Rssi                 int32    `protobuf:"varint,5,opt,name=rssi,proto3" json:"rssi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseStation) Reset()         { *m = BaseStation{} }
func (m *BaseStation) String() string { return proto.CompactTextString(m) }
func (*BaseStation) ProtoMessage()    {}
func (*BaseStation) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cb77491feb77e2e, []int{4}
}

func (m *BaseStation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseStation.Unmarshal(m, b)
}
func (m *BaseStation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseStation.Marshal(b, m, deterministic)
}
func (m *BaseStation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseStation.Merge(m, src)
}
func (m *BaseStation) XXX_Size() int {
	return xxx_messageInfo_BaseStation.Size(m)
}
func (m *BaseStation) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseStation.DiscardUnknown(m)
}

var xxx_messageInfo_BaseStation proto.InternalMessageInfo

func (m *BaseStation) GetMcc() int32 {
	if m != nil {
		return m.Mcc
	}
	return 0
}

func (m *BaseStation) GetMnc() int32 {
	if m != nil {
		return m.Mnc
	}
	return 0
}

func (m *BaseStation) GetLac() int32 {
	if m != nil {
		return m.Lac
	}
	return 0
}

func (m *BaseStation) GetCi() int32 {
	if m != nil {
		return m.Ci
	}
	return 0
}

func (m *BaseStation) GetRssi() int32 {
	if m != nil {
		return m.Rssi
	}
	return 0
}

func init() {
	proto.RegisterEnum("LocationPacket_Status", LocationPacket_Status_name, LocationPacket_Status_value)
	proto.RegisterType((*Lock)(nil), "Lock")
	proto.RegisterType((*LockStatus)(nil), "LockStatus")
	proto.RegisterType((*LocationPacket)(nil), "LocationPacket")
	proto.RegisterType((*PositionPackage)(nil), "PositionPackage")
	proto.RegisterType((*BaseStation)(nil), "BaseStation")
}

func init() { proto.RegisterFile("bl10.proto", fileDescriptor_7cb77491feb77e2e) }

var fileDescriptor_7cb77491feb77e2e = []byte{
	// 661 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0xdf, 0x6e, 0xda, 0x3c,
	0x14, 0x6f, 0x02, 0xc9, 0x07, 0x27, 0x14, 0xf8, 0xac, 0xae, 0x62, 0xb4, 0xeb, 0x3a, 0xa4, 0x49,
	0xbd, 0x98, 0xd2, 0x96, 0x49, 0xd3, 0x6e, 0x43, 0xc9, 0x3a, 0xb6, 0x14, 0x90, 0x09, 0xea, 0x76,
	0x15, 0x19, 0xe3, 0xa5, 0x16, 0x81, 0x44, 0x38, 0x5c, 0xf4, 0x41, 0xf6, 0x00, 0x7b, 0x85, 0xbd,
	0xcd, 0x1e, 0x61, 0x6f, 0x31, 0xd9, 0x49, 0xa0, 0xad, 0xd4, 0xbb, 0xf3, 0xfb, 0x63, 0x1f, 0x1f,
	0x9f, 0x63, 0x03, 0xcc, 0xa2, 0xcb, 0x0b, 0x3b, 0x59, 0xc7, 0x69, 0xdc, 0x3e, 0x0a, 0xe3, 0x38,
	0x8c, 0xd8, 0xb9, 0x42, 0xb3, 0xcd, 0x8f, 0x73, 0xb6, 0x4c, 0xd2, 0xfb, 0x4c, 0xec, 0xb4, 0xa1,
	0xec, 0xc5, 0x74, 0x81, 0x10, 0x94, 0xf9, 0x92, 0xf1, 0x96, 0x76, 0xaa, 0x9d, 0x55, 0xb1, 0x8a,
	0x3b, 0x7f, 0x34, 0x00, 0x29, 0x4e, 0x52, 0x92, 0x6e, 0x04, 0x3a, 0x86, 0x6a, 0xca, 0x97, 0x4c,
	0xa4, 0x64, 0x99, 0x28, 0x5f, 0x09, 0xef, 0x88, 0xed, 0x06, 0xfa, 0x6e, 0x03, 0xf4, 0x1a, 0xac,
	0x30, 0x11, 0x01, 0x5b, 0x91, 0x59, 0xc4, 0xe6, 0xad, 0xd2, 0xa9, 0x76, 0x56, 0xc1, 0x10, 0x26,
	0xc2, 0xcd, 0x18, 0xf4, 0x06, 0x6a, 0x5c, 0x04, 0xf4, 0x8e, 0xac, 0xe9, 0x1d, 0x5f, 0x85, 0xad,
	0xb2, 0x72, 0x58, 0x5c, 0x5c, 0x15, 0x14, 0x3a, 0x82, 0x2a, 0x17, 0x41, 0x14, 0xd3, 0x05, 0x9b,
	0xb7, 0x0c, 0xa5, 0x57, 0xb8, 0xf0, 0x14, 0x46, 0x1f, 0xa1, 0x11, 0xc5, 0x94, 0xa4, 0x3c, 0x5e,
	0x05, 0x09, 0xa1, 0x0b, 0x96, 0xb6, 0xcc, 0x53, 0xed, 0xcc, 0xea, 0x36, 0x6c, 0x2f, 0xe7, 0xc7,
	0x8a, 0xc6, 0xf5, 0xe8, 0x11, 0xee, 0xfc, 0x2e, 0x41, 0xfd, 0xb1, 0x05, 0xbd, 0x05, 0x69, 0x5a,
	0x04, 0x4f, 0x8b, 0xdc, 0x97, 0xac, 0xbf, 0x2d, 0xf4, 0x1d, 0x54, 0x8a, 0xbd, 0x54, 0xb1, 0x56,
	0xb7, 0x69, 0x8f, 0x63, 0xc1, 0x8b, 0x9d, 0x48, 0xc8, 0xf0, 0xd6, 0x81, 0x6c, 0x30, 0x85, 0xba,
	0x3e, 0x55, 0x7d, 0xbd, 0x7b, 0xf8, 0xe4, 0x60, 0x76, 0x76, 0xb9, 0x38, 0x77, 0xa1, 0x73, 0xa8,
	0xcd, 0x88, 0x60, 0x81, 0x84, 0x32, 0x43, 0x59, 0x65, 0xa8, 0xd9, 0x3d, 0x22, 0xd8, 0x24, 0xe3,
	0xb0, 0x35, 0xdb, 0x81, 0xce, 0x5f, 0x0d, 0xcc, 0xbc, 0x41, 0xff, 0xc3, 0xbe, 0x3f, 0xb8, 0x19,
	0x0c, 0xaf, 0x03, 0xec, 0x8e, 0x47, 0xd8, 0x6f, 0xee, 0xa1, 0x97, 0xf0, 0xe2, 0xd3, 0xe0, 0x9b,
	0xdb, 0x0f, 0xfa, 0x83, 0x89, 0xef, 0x0c, 0xaf, 0xdc, 0x42, 0xd2, 0x50, 0x13, 0x6a, 0xd7, 0xe3,
	0x49, 0x80, 0xdd, 0xe9, 0xd8, 0x1b, 0x39, 0xfd, 0xa6, 0x8e, 0x1a, 0x60, 0x79, 0x5f, 0xfa, 0xb7,
	0x85, 0xa5, 0xa4, 0x88, 0xd1, 0xd5, 0xd7, 0x82, 0x28, 0xcb, 0x0c, 0xd3, 0xe1, 0x43, 0xca, 0x40,
	0x27, 0xd0, 0xf6, 0x46, 0xb7, 0xc1, 0x60, 0xe8, 0xbb, 0x78, 0xe8, 0x78, 0x41, 0xcf, 0xf1, 0x7d,
	0x17, 0x7f, 0x0f, 0x1c, 0xcf, 0xc1, 0x37, 0x4d, 0x13, 0xb5, 0xe0, 0x40, 0xea, 0x05, 0x3d, 0xf9,
	0x3c, 0xf5, 0xfb, 0xa3, 0xdb, 0x61, 0xf3, 0x3f, 0x84, 0xa0, 0xee, 0xf4, 0x86, 0x23, 0x7c, 0xe3,
	0x78, 0xb9, 0xbb, 0x82, 0x8e, 0xa1, 0xb5, 0xe5, 0xb2, 0x4c, 0xb2, 0x9c, 0x4c, 0xad, 0x76, 0x7e,
	0x6a, 0xd0, 0x78, 0x72, 0xd5, 0xa8, 0x0d, 0x95, 0x88, 0xa4, 0x3c, 0xdd, 0xcc, 0x99, 0xea, 0x97,
	0x8e, 0xb7, 0x58, 0x4e, 0x6c, 0x14, 0xaf, 0xc2, 0x4c, 0xd4, 0x95, 0xb8, 0x23, 0xe4, 0x4a, 0x42,
	0xe9, 0x66, 0x4d, 0xe8, 0xbd, 0x6a, 0x8e, 0x8e, 0xb7, 0x18, 0x1d, 0x82, 0x49, 0xe3, 0xcd, 0x5a,
	0x30, 0xd5, 0x00, 0x03, 0xe7, 0x08, 0x1d, 0x80, 0x21, 0x12, 0x96, 0x4f, 0xa2, 0x8e, 0x33, 0xd0,
	0x09, 0xc1, 0x7a, 0xd0, 0x1f, 0xd4, 0x84, 0xd2, 0x92, 0x52, 0x75, 0x1a, 0x03, 0xcb, 0x50, 0x31,
	0x2b, 0xaa, 0x8e, 0x20, 0x99, 0x95, 0x62, 0x22, 0x42, 0x55, 0x5e, 0x03, 0xcb, 0x10, 0xd5, 0x41,
	0xa7, 0x3c, 0x4f, 0xa7, 0x53, 0x2e, 0x1f, 0xd4, 0x5a, 0x08, 0xae, 0x32, 0x19, 0x58, 0xc5, 0xdd,
	0x5f, 0x1a, 0x54, 0x7a, 0xde, 0xe5, 0x85, 0x7a, 0xb2, 0x27, 0x60, 0x4e, 0x57, 0x72, 0x36, 0x91,
	0x21, 0x87, 0x6a, 0xd1, 0xb6, 0xec, 0xdd, 0x6b, 0xed, 0xec, 0xa1, 0x57, 0x60, 0x38, 0x11, 0x59,
	0x2f, 0x9f, 0x91, 0x4f, 0xc0, 0x54, 0xa3, 0xc8, 0x9e, 0xd1, 0x3f, 0xc0, 0x7e, 0x16, 0x4f, 0x93,
	0x39, 0x49, 0x99, 0x40, 0x87, 0x76, 0xf6, 0x91, 0xd8, 0xc5, 0x47, 0x62, 0xbb, 0xf2, 0x23, 0x79,
	0xb4, 0xee, 0x42, 0x9b, 0x99, 0x4a, 0x7e, 0xff, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xaf, 0x16, 0x90,
	0xae, 0x83, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BL10LockClient is the client API for BL10Lock service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BL10LockClient interface {
	Unlock(ctx context.Context, in *Lock, opts ...grpc.CallOption) (*LockStatus, error)
	Alarm(ctx context.Context, in *Lock, opts ...grpc.CallOption) (*LockStatus, error)
	Locate(ctx context.Context, in *Lock, opts ...grpc.CallOption) (*LockStatus, error)
	StatusUpdates(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (BL10Lock_StatusUpdatesClient, error)
}

type bL10LockClient struct {
	cc *grpc.ClientConn
}

func NewBL10LockClient(cc *grpc.ClientConn) BL10LockClient {
	return &bL10LockClient{cc}
}

func (c *bL10LockClient) Unlock(ctx context.Context, in *Lock, opts ...grpc.CallOption) (*LockStatus, error) {
	out := new(LockStatus)
	err := c.cc.Invoke(ctx, "/BL10Lock/Unlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bL10LockClient) Alarm(ctx context.Context, in *Lock, opts ...grpc.CallOption) (*LockStatus, error) {
	out := new(LockStatus)
	err := c.cc.Invoke(ctx, "/BL10Lock/Alarm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bL10LockClient) Locate(ctx context.Context, in *Lock, opts ...grpc.CallOption) (*LockStatus, error) {
	out := new(LockStatus)
	err := c.cc.Invoke(ctx, "/BL10Lock/Locate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bL10LockClient) StatusUpdates(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (BL10Lock_StatusUpdatesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BL10Lock_serviceDesc.Streams[0], "/BL10Lock/StatusUpdates", opts...)
	if err != nil {
		return nil, err
	}
	x := &bL10LockStatusUpdatesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BL10Lock_StatusUpdatesClient interface {
	Recv() (*LockStatus, error)
	grpc.ClientStream
}

type bL10LockStatusUpdatesClient struct {
	grpc.ClientStream
}

func (x *bL10LockStatusUpdatesClient) Recv() (*LockStatus, error) {
	m := new(LockStatus)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BL10LockServer is the server API for BL10Lock service.
type BL10LockServer interface {
	Unlock(context.Context, *Lock) (*LockStatus, error)
	Alarm(context.Context, *Lock) (*LockStatus, error)
	Locate(context.Context, *Lock) (*LockStatus, error)
	StatusUpdates(*empty.Empty, BL10Lock_StatusUpdatesServer) error
}

// UnimplementedBL10LockServer can be embedded to have forward compatible implementations.
type UnimplementedBL10LockServer struct {
}

func (*UnimplementedBL10LockServer) Unlock(ctx context.Context, req *Lock) (*LockStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unlock not implemented")
}
func (*UnimplementedBL10LockServer) Alarm(ctx context.Context, req *Lock) (*LockStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Alarm not implemented")
}
func (*UnimplementedBL10LockServer) Locate(ctx context.Context, req *Lock) (*LockStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Locate not implemented")
}
func (*UnimplementedBL10LockServer) StatusUpdates(req *empty.Empty, srv BL10Lock_StatusUpdatesServer) error {
	return status.Errorf(codes.Unimplemented, "method StatusUpdates not implemented")
}

func RegisterBL10LockServer(s *grpc.Server, srv BL10LockServer) {
	s.RegisterService(&_BL10Lock_serviceDesc, srv)
}

func _BL10Lock_Unlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Lock)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BL10LockServer).Unlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BL10Lock/Unlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BL10LockServer).Unlock(ctx, req.(*Lock))
	}
	return interceptor(ctx, in, info, handler)
}

func _BL10Lock_Alarm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Lock)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BL10LockServer).Alarm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BL10Lock/Alarm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BL10LockServer).Alarm(ctx, req.(*Lock))
	}
	return interceptor(ctx, in, info, handler)
}

func _BL10Lock_Locate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Lock)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BL10LockServer).Locate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BL10Lock/Locate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BL10LockServer).Locate(ctx, req.(*Lock))
	}
	return interceptor(ctx, in, info, handler)
}

func _BL10Lock_StatusUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BL10LockServer).StatusUpdates(m, &bL10LockStatusUpdatesServer{stream})
}

type BL10Lock_StatusUpdatesServer interface {
	Send(*LockStatus) error
	grpc.ServerStream
}

type bL10LockStatusUpdatesServer struct {
	grpc.ServerStream
}

func (x *bL10LockStatusUpdatesServer) Send(m *LockStatus) error {
	return x.ServerStream.SendMsg(m)
}

var _BL10Lock_serviceDesc = grpc.ServiceDesc{
	ServiceName: "BL10Lock",
	HandlerType: (*BL10LockServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Unlock",
			Handler:    _BL10Lock_Unlock_Handler,
		},
		{
			MethodName: "Alarm",
			Handler:    _BL10Lock_Alarm_Handler,
		},
		{
			MethodName: "Locate",
			Handler:    _BL10Lock_Locate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StatusUpdates",
			Handler:       _BL10Lock_StatusUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "bl10.proto",
}
